name: Tests

on:
  push

jobs:
  test:
    name: Le Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: Test W1/7 sparsearray
      run: |
        python w1/7_sparsearray.py
    - name: Test W2/1 - lonely integer
      run: |
        python w2/lonely.py
    - name: Test W2/2 - grading students
      run: |
        python w2/grading.py
    - name: Test W2/6 - counting valleys
      run: |
        python w2/valleys.py
    - name: Test W2/7 - pangrams
      run: |
        python w2/pangrams.py
    - name: Test W2/8 - mars
      run: |
        python w2/mars.py