name: Tests

on:
  push

jobs:
  test:
    name: Le Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: WK1 tests
      run: |
        python w1/7_sparsearray.py
    - name: WK2 tests
      run: |
        python w2/lonely.py
        python w2/grading.py
        python w2/bits.py
        python w2/diagonal.py
        python w2/counting.py
        python w2/valleys.py
        python w2/pangrams.py
        python w2/mars.py
        python w2/matrix.py
    - name: WK3 tests
      run: |
        python w3/permuting/permuting.py
        python w3/subarray2/subarray.py
        python w3/xor.py