name: Tests

on:
  push

jobs:
  elixir-dialyzer:
    if: contains(github.ref, 'elixir/')
    name: Dialyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.3'
          otp-version: '27.3.2'

      - name: Install dependencies
        run: mix deps.get

      # - name: Cache Dialyzer PLT
      #   uses: actions/cache@v3
      #   with:
      #     path: _build/dev/dialyxir_*
      #     key: plt-${{ runner.os }}-${{ hashFiles('mix.lock') }}
      #     restore-keys: |
      #       plt-${{ runner.os }}-

      - name: Compile
        run: mix compile

      - name: Run Dialyzer
        run: mix dialyzer

  elixir-test:
    if: contains(github.ref, 'elixir/')
    name: Test Elixir
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-24.04]
        otp: [27.x]
        elixir: [1.18.3]
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run tests
        run: |
          mix compile --force --
          mix test w1
  test-go:
    if: contains(github.ref, 'go/')
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: (Go) WK1 tests
        working-directory: w1
        run: go test -v

  python-pylint:
    if: contains(github.ref, 'python/') 
    name: Pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Set up virtualenv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements_test.txt
        pip install pylint
    - name: (Python) Pylint
      run: |
        source venv/bin/activate
        pylint w1/

  python-test:
    if: contains(github.ref, 'python/')
    name: Test Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: (Python) tests
      run: python -m unittest -v */*_test.py
    - name: (Python) WK2 tests
      run: |
        python w2/lonely.py
        python w2/grading.py
        python w2/bits.py
        python w2/diagonal.py
        python w2/counting.py
        python w2/valleys.py
        python w2/pangrams.py
        python w2/mars.py
        python w2/matrix.py
    - name: (Python) WK3 tests
      run: |
        python w3/permuting.py
        python w3/subarray.py
        python w3/xor.py
        python w3/migratory.py
        python w3/triangle.py
        python w3/zigzag.py
        python w3/exam_two_sets.py
        python w3/pages.py
    - name: (Python) WK4 tests
      run: |
        python w4/numbers.py
        python w4/rotation.py
        python w4/jumps.py
        python w4/beautiful.py
        python w4/closest.py
        python w4/towers.py
        python w4/mindiff.py
        python w4/ceasar.py
    - name: (Python) WK5 tests
      run: |
          python w5/maxmin.py
          python w5/passwd.py
  test-typescript:
    if: contains(github.ref, 'typescript/')
    name: Test TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Run Vitest
        run: pnpm vitest run