name: Tests

on:
  push

jobs:
  test-elixir:
    if: contains(github.ref, 'elixir/')
    name: Test Elixir
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-24.04]
        otp: [27.x]
        elixir: [1.18.3]
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run tests
        run: |
          mix compile --force --
          mix test w1
  test-go:
    if: contains(github.ref, 'go/')
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: (Go) WK1 tests
        working-directory: w1
        run: go test -run Test_plus_minus
  test-python:
    if: contains(github.ref, 'python/')
    name: Test Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: (Python) WK1 tests
      run: |
        python w1/7_sparsearray.py
    - name: (Python) WK2 tests
      run: |
        python w2/lonely.py
        python w2/grading.py
        python w2/bits.py
        python w2/diagonal.py
        python w2/counting.py
        python w2/valleys.py
        python w2/pangrams.py
        python w2/mars.py
        python w2/matrix.py
    - name: (Python) WK3 tests
      run: |
        python w3/permuting.py
        python w3/subarray.py
        python w3/xor.py
        python w3/migratory.py
        python w3/triangle.py
        python w3/zigzag.py
        python w3/exam_two_sets.py
        python w3/pages.py
    - name: (Python) WK4 tests
      run: |
        python w4/numbers.py
        python w4/rotation.py
        python w4/jumps.py
        python w4/beautiful.py
        python w4/closest.py
        python w4/towers.py
        python w4/mindiff.py
        python w4/ceasar.py
    - name: (Python) WK5 tests
      run: |
          python w5/maxmin.py
          python w5/passwd.py
